connectedin/connectedin/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('perfis.urls')),
    url(r'^', include('usuarios.urls')),
]

connectedin/perfis/urls.py
from django.conf.urls import url
from perfis import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^perfil/(?P<perfil_id>\d+)$', views.exibir, name='exibir'),
    url(r'^perfil/(?P<perfil_id>\d+)/convidar$',
        views.convidar, name='convidar'),

    url(r'^perfil/(?P<convite_id>\d+)/aceitar$',
        views.aceitar, name='aceitar'),
]

connectedin/usuarios/urls.py
from django.conf.urls import url
from .views import RegistrarUsuarioView
from django.contrib.auth import views

urlpatterns = [
    url(r'^registrar/$', RegistrarUsuarioView.as_view(),name='registrar'),
    url(r'^login/$', views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(template_name='login.html'), name='logout'),
]

connectedin/perfis/models.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    #email = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=255, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self')
    usuario = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)

    @property
    def email(self):
        return self.usuario.email

    def convidar(self, perfil_convidado):
        c = Convite(solicitante=self, convidado=perfil_convidado)
        c.save()


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, related_name='convites_recebidos')

    def aceitar(self):
        self.solicitante.contatos.add(self.convidado)
        self.convidado.contatos.add(self.solicitante)
        self.delete()

connectedin/usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django import forms
from django.contrib.auth.models import User


class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):

        valid = True

        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_mensagem('Verifique seus campos.')
            valid = False

        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if user_exists:
            self.adiciona_mensagem('Já existe um usuário cadastrado com esse nome.')
            valid = False

        return valid

    def adiciona_mensagem(self, mensagem):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,
                                         forms.utils.ErrorList())

        errors.append(mensagem)

connectedin/perfis/views.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.shortcuts import render, redirect
from .models import Perfil, Convite
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def index(request):
    perfis = Perfil.objects.all()
    contexto = {'perfis': perfis,
                'perfil_logado': get_perfil_logado(request)}

    return render(request, 'index.html', contexto)

@login_required
def exibir(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    ja_eh_contato = perfil in perfil_logado.contatos.all()
    contexto = {'perfil': perfil,
                'perfil_logado': perfil_logado,
                'ja_eh_contato': ja_eh_contato}

    return render(request, 'perfil.html', contexto)

@login_required
def convidar(request, perfil_id):
    perfil_convidado = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    perfil_logado.convidar(perfil_convidado)
    return redirect('index')


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')


@login_required
def get_perfil_logado(request):
    return request.user.perfil

connectedin/usuarios/views.py
# -*- coding: utf-8 -*-
#from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic.base import View
from usuarios.forms import RegistrarUsuarioForm
from django.contrib.auth.models import User
from perfis.models import Perfil


# Create your views here.

class RegistrarUsuarioView(View):
    template = 'registrar.html'

    def get(self, request):
        return render(request, self.template)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)

        if form.is_valid():
            dados = form.cleaned_data
            usuario = User.objects.create(username=dados['nome'],
                                          email=dados['email'],
                                          password=dados['senha'])

            perfil = Perfil(nome=dados['nome'],
                            telefone=dados['telefone'],
                            nome_empresa=dados['nome_empresa'],
                            usuario=usuario)
            perfil.save()
            return redirect('index')

        return render(request, self.template, {'form': form})

connectedin/perfis/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang = "pt-br">
	<head>
		<meta charset="utf-8">
		<title>ConnectedIn</title>
		<link rel="stylesheet" 
			 href="{% static 'styles/bootstrap.css' %}">
		<link rel="stylesheet" 
			 href="{% static 'styles/main.css' %}">

	</head>
	<body>
		<div class="container">
			<div class = "header">
				<ul class = "nav nav-pills pull-right">
					<li><a href = "{% url 'index' %}">{{ perfil_logado.nome }}</a></li>
					<li><a href = "/logout/">Logout</a></li>
				</ul>
				<h3 class = "text-muted">ConnectedIn</h3>
			</div>
			
			<div class="row content">
				{% block body%}
				{% endblock %}				
			</div>		
		</div>	
	</body>
</html>

connectedin/perfis/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="col-lg-12"> 		
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os perfis</strong>
		</div>
		{% if perfis %}
		<ul >
			{% for perfil in perfis %}
				<li>
					<a href = "{% url 'exibir' perfil.id %}">	{{ perfil.nome }} / {{ perfil.email }}
					</a>	
				</li>
			{% endfor %}
		{% else %}	
			<p>Não há perfis cadastrados</p>
		{% endif %}
		</ul>
	</div>	

	<div class="panel panel-default">
		{% with total_convites=perfil_logado.convites_recebidos.count %}
		{% if total_convites %}
			<div class="panel-heading">
				<strong>
					Você tem {{ total_convites }}
					convite{{ total_convites | pluralize}}
				</strong>
			</div>
			<ul class = "list-group">
				{% for convite in perfil_logado.convites_recebidos.all %}
					<li class="list-group-item">
						{{ convite.solicitante.nome }}
						<a href = "{% url 'aceitar' convite.id %}" class="pull-right">aceitar</a>
					</li>
				{% endfor %}	
		 	</ul>
		{% else %}				
			<div class = "panel-body">
				<p>Nenhumm convite recebido :(</p>
			</div>
		{% endif %}
		{% endwith %}
	</div>
	
	<div class="panel panel-default">
		{% with total_contatos=perfil_logado.contatos.count %}
		{% if total_contatos %}
			<div class="panel-heading">
				<strong>
					Você tem {{ total_contatos }}
					contato{{ total_contatos | pluralize}}
				</strong>
			</div>
			<ul class = "list-group">
				{% for contato in perfil_logado.contatos.all %}
					<li class="list-group-item">
						<a href = "{% url 'exibir' contato.id %}">
							{{ contato.nome }} // {{ contato.email}}
						 </a>
					</li>
				{% endfor %}	
		 	</ul>
		{% else %}				
			<div class = "panel-body">
				<p>Nenhum contato :(</p>
			</div>
		{% endif %}
		{% endwith %}
	</div>

</div>
{% endblock %}

connectedin/perfis/templates/perfil.html
{% extends 'base.html' %}
{% block body %}
<div class = "col-lg-12">
		<h2 style="margin-top: 0px">{{ perfil.nome }}</h2>
		<address>			
			<a href = "mailto:{{ perfil.email }}">{{ perfil.email }}</a>
			<br>
			<strong>{{ perfil.nome_empresa }}</strong>
		
		</address>

		{% if ja_eh_contato %}
			<div class = "well well-sm">Vocês já estão conectados</div>
		{% else %}	
			<a href = "{% url 'convidar' perfil.id %}">
				Convidar
			</a>	
		{% endif %}	
</div>		
{% endblock %}		

connectedin/usuarios/templates/base_usuario.html
<!doctype html>
{% load staticfiles %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <title>ConnectedIn</title>
    <link rel="stylesheet"
          href="{% static 'styles/bootstrap.css' %}">
    <link rel="stylesheet"
          href="{% static 'styles/signin.css' %}">

</head>
<body>
<div class="container">
    {% block body%}
    {% endblock %}
</div>
</div>
</body>
</html>

connectedin/usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

<form class="form-signin" role="form"
      action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>
    <input type="text" id="id_username" name="username"
           class="form-control" placeholder="Nome" required autofocus>
    <input type="password" id="id_password" name="password"
           class="form-control" placeholder="Senha" required>
    <button class="btn btn-lg btn-primary btn-block"
            type="submit" value="Login">Login
    </button>
    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close"
                data-dismiss="alert" aria-hidden="true">×
        </button>
        Por favor, verifique o Email e/ou Senha informados
    </div>
    {% endif %}
    <a href="{% url 'registrar' %}">Registre-se</a>
</form>

{% endblock %}

connectedin/usuarios/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}
<form class="form-signin" method="post" action="{% url 'registrar' %}">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>
    <input class="form-control" placeholder="E-mail *"
           id="id_email" name="email" autofocus required>
    <input class="form-control"
           placeholder="Nome *" id="id_nome" name="nome" required>
    <input class="form-control"
           placeholder="Senha *" id="id_senha" name="senha" type="password" required>
    <hr>
    <input class="form-control" placeholder="Telefone *"
           id="id_telefone" name="telefone" required>
    <input class="form-control" placeholder="Nome da empresa"
           id="id_nome_empresa" name="nome_empresa" required>
    <hr>
    <button type="submit"
            class="btn btn-lg btn-primary btn-block">Registrar
    </button>
</form>
{% endblock %}